kind = "web"
previewPath = "/"
title = "Radar Interestelar CCEE"
version = "1.0.0"
id = "artifacts/radar-interestelar"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 3000

[services.development]
run = "pnpm --filter @workspace/radar-interestelar run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/radar-interestelar", "run", "build" ]
publicDir = "artifacts/radar-interestelar/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "3000"
BASE_PATH = "/"
